# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=150)),
                ('pub_date', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
    ]
