# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160608_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='pub_date',
            field=models.CharField(max_length=15),
        ),
    ]
